name: Bukkit-Web-Server
version: ${project.version}
main: tv.ph16.bukkitwebserver.Plugin
api-version: 1.15
load: STARTUP
authors: [ Shmuelie ]
description: Adds an HTTP Server to Bukkit
author: Shmuelie
database: false
commands:
  web:
    description: "Start and stop web server"
    usage: "/web start|stop|port <n>|start <n>"
libraries:
  - org.apache.tika:tika-core:1.24.1
  - org.jetbrains:annotations:20.1.0