# yaml-language-server: $schema=https://json.schemastore.org/bukkit-plugin.json
name: Bukkit-Web-Server
version: ${project.version}
main: tv.ph16.bukkitwebserver.Plugin
api-version: 1.15
load: STARTUP
authors: [ Shmuelie ]
description: Adds an HTTP Server to Bukkit
author: Shmuelie
database: false
libraries:
  - org.jetbrains:annotations:20.1.0
  - org.eclipse.jetty:jetty-server:11.0.2
  - org.slf4j:slf4j-jdk14:2.0.0-alpha1
website: https://github.com/PH16-Productions/tv.ph16.bukkitwebserver