# yaml-language-server: $schema=https://json.schemastore.org/bukkit-plugin.json
name: PaperMC-HTTP-Server
version: ${project.version}
main: tv.ph16.papermchttpserver.Plugin
api-version: 1.16
load: STARTUP
authors: [ Shmuelie ]
description: Adds a HTTP Server to PaperMC. By default no servers are included. Public API provides support for adding, getting, and remove servers.
author: Shmuelie
database: false
libraries:
  - org.jetbrains:annotations:20.1.0
  - org.eclipse.jetty:jetty-server:11.0.2
  - org.slf4j:slf4j-jdk14:2.0.0-alpha1
website: https://github.com/PH16-Productions/tv.ph16.papermchttpserver